services:
  postgres:
    image: postgres:15
    container_name: fundamentus_postgres
    environment:
      POSTGRES_DB: fundamentus
      POSTGRES_USER: fundamentus
      POSTGRES_PASSWORD: fundamentus
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  app:
    build: .
    container_name: fundamentus_app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: fundamentus
      DB_USER: fundamentus
      DB_PASS: fundamentus
    volumes:
      - ./:/app
    restart: always

volumes:
  postgres_data:
