name: "Deploy para VPS"
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Build da aplicação"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            APP_DIR="/var/www/crawler-fundamentus-python"
            REPO_URL="git@github.com:alexandre-costa-81/crawler-fundamentus-python.git"

            if [ ! -d "$APP_DIR" ]; then
              echo "Diretório não existe. Clonando repositório..."
              git clone "$REPO_URL" "$APP_DIR"
            else
              echo "Diretório existe. Atualizando repositório..."
              cd "$APP_DIR"
              git pull
            fi

            echo "Build da aplicação com Docker Compose"
            cd "$APP_DIR"
            docker-compose up -d --build
